require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, '14.0'
# prepare_react_native_project!
# pod 'OpenSSL-Universal'


setup_permissions([
# 'AppTrackingTransparency',
# 'Bluetooth',
# 'Calendars',
# 'CalendarsWriteOnly',
# 'Camera',
# 'Contacts',
# 'FaceID',
'LocationAccuracy',
'LocationAlways',
'LocationWhenInUse',
'MediaLibrary',
# 'Microphone',
# 'Motion',
# 'Notifications',
'PhotoLibrary',
# 'PhotoLibraryAddOnly',
# 'Reminders',
# 'Siri',
# 'SpeechRecognition',
# 'StoreKit',
])


def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')



target 'orthoceph' do
  config = use_native_modules!

  use_react_native!(
  :path => config[:reactNativePath],
  :hermes_enabled => false)

  

  # target 'orthocephTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.6.0' })
  # use_flipper!({ 'Flipper' => '0.78.0' })
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
  
end



# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
#    end
#   end
#  end

# target 'orthoceph-tvOS' do
#   # Pods for orthoceph-tvOS

#   target 'orthoceph-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end

